### ISSUE TITLE
Buzzwords

### ISSUE THREAD

**Issue by imml3457** [mduraney/MiniProject1#1]
I have the idea of doing text analysis on recent CS articles to see how many of the articles use buzzwords, and to see what the highest percentages of them are. 

The list of buzzwords are of course subjective but I will be adding several hot topic buzzwords from suggestions online.

**Comment by mduraney** [comment]
I think this is a really good idea! I would be very interested in seeing these results, especially being a CS major, I am curious as to what buzzwords are most commonly used in the field. Do you have any idea about what specific sources you will use for the recent CS articles?

**Comment by imml3457** [comment]
I was thinking about using hacker news and some academic articles (from recent journals or conferences i.e. ACM's recent articles).
